version: '2'


volumes:
  wiki-data:
    external: true


services:
  # common services

  nginx:
    image: nginx:1.11
    restart: always
    build:
      context: ./images/nginx
    depends_on:
      - accounts
      - innopoints
      - innowiki
    ports:
      - "8770:8770"
    volumes:
      - "./images/services/innowiki/img/favicon.ico:/etc/nginx/html/favicon.ico:ro"
  
  mongodb:
    image: mongo:3.3
    restart: always
  
  mysql:
    image: mysql:5.5
    restart: always

  # microservices
  
  accounts:
    image: accounts
    restart: always
    build:
      context: ./images/microservices/accounts
    depends_on:
      - mongodb
  
  innopoints:
    image: innopoints
    restart: always
    build: 
      context: ./images/microservices/innopoints
    depends_on:
      - mysql
      - accounts

  # other services

  innowiki:
    image: ratijas/moinmoin
    build:
      context: ./images/services/innowiki
    command: -t Europe/Moscow
    env_file:
      - wiki.env
    volumes:
      - "wiki-data:/usr/local/share/moin/data"



