version: '2'


services:
  # common services

  nginx:
    build:
      dockerfile: dev.Dockerfile
    volumes:
       - /home/frontend/test_frontend:/srv/frontend
    ports:
      - "8770:8770"

  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  
  # microservices

  accounts:
    build:
      dockerfile: dev.Dockerfile
      args:
        - ACCOUNTS_VERSION=1.0 # exposed from an environment variable
        - WEB_HOST=0.0.0.0
        - WEB_PORT=5000
        - DB_HOST=mongodb
        - DB_PORT=27017
    volumes:
      - ./data/dev/accounts:/srv/accounts

  innopoints:
    build:
      dockerfile: dev.Dockerfile
      args:
        - INNOPOINTS_VERSION=1.0 # exposed from an environment variable
        - WEB_HOST=0.0.0.0
        - WEB_PORT=4567
        - DB_HOST=mysql
        - DB_PORT=3306
        - ACCOUNTS_HOST=accounts
        - ACCOUNTS_PORT=5000
        - ACCOUNTS_VERSION=1.0 # exposed from an environment variable
    volumes:
      - ./data/dev/innopoints:/srv/innopoints
  
  # other services

  innowiki:
    build:
      dockerfile: dev.Dockerfile



